language: python
python:
  - "2.7"
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install -qq python-numpy python-scipy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install -qq python3-numpy python3-scipy; fi
install:
  - pip install .
script:
  - toeplitz-runtests
after_success:
notifications:
    email: false