language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update -qq
  - sudo apt-cache depends -qq python-numpy python-scipy
  - sudo apt-get install -qq python-numpy python-scipy
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install --use-mirrors numpy scipy; fi
install:
  - pip install . --use-mirrors
script:
  - toeplitz-runtests
after_success:
notifications:
    email: false