language: c
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.7
before_install:
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      GF="gfortran_osx-64";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      GF="gfortran_linux-64";
    else
      GF="";
    fi
  - conda config --add channels conda-forge
  - conda create -q -n testenv python=$PYTHON_VERSION numpy scipy $GF
  - conda activate testenv
  - conda list
install:
  - pip install -v --no-deps .
script:
  - mkdir empty; cd empty
  - toeplitz-runtests
after_success:
notifications:
    email: false
